//using Npgsql;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mail;
using System.Threading.Tasks;

namespace AzUtil.Core
{


    public interface IAzUtil
    {
        //Task<DataTable> SqlQueryAsync(string query, string connStr, params object[] Inputs);
        Task SendMail(SMTPSettings sMTP);
    }
    public class Utilities : IAzUtil
    {
        public static int MySQLTimeout = 0;

        

        public async Task SendMail(SMTPSettings sMTP)
        {
            SmtpClient client = new SmtpClient(sMTP.Host, sMTP.Port)
            {
                EnableSsl = sMTP.UseSsl,   
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(sMTP.UN, sMTP.PW) //tHIS PASSWORD WAS generated by google special app access https://myaccount.google.com/apppasswords
            };
            MailMessage mailMessage = new MailMessage
            {
                From = new MailAddress(sMTP.MailFrom)
            };
            foreach (var mailTo in sMTP.MailTos) mailMessage.To.Add(mailTo);
            foreach (var mailTo in sMTP.MailBccs) mailMessage.Bcc.Add(mailTo);
            foreach (var mailTo in sMTP.MailCcs) mailMessage.CC.Add(mailTo);
            mailMessage.IsBodyHtml = true;
            mailMessage.Subject = sMTP.MailSubject;
            mailMessage.Body = sMTP.MailBody;
            await client.SendMailAsync(mailMessage);
        }
    }


    public class SMTPSettings
    {
        public string Host = "127.0.0.1";
        public int Port = 587;
        public bool UseSsl = true;
        public string UN = "";
        public string PW = "";
        public string MailFrom;
        public List<string> MailTos = new List<string>();
        public List<string> MailBccs = new List<string>();
        public List<string> MailCcs = new List<string>();
        public string MailBody;
        public string MailSubject;
    }
}
